### ISSUE TITLE
Delete record not working. 

### ISSUE THREAD

**Issue by jrahaim** [whitetown/cdbfapiPlus#1]
Swift 4, OSX. 

Registered user. read, Append, write all working.
code:

```swift
dbf.deleteRecord(recordNumber)
dbf.writeRecord(recordNumber)
dbf.closeDBFfile()
```

The record isn't marked deleted.

This particular record is the last record in the DB.

**Comment by whitetown** [comment]
`dbf.deleteRecord(...)` 
physically deletes a record from a table.
You have to use another function:
`dbf.markAsDeleted(recordNumber)`
[https://whitetown.com/cdbfapi/markAsDeleted/swift/](https://whitetown.com/cdbfapi/markAsDeleted/swift/)

**Comment by whitetown** [comment]
I guess it's resolved
